# Ipan was here
alias edit='vim'
alias listenlinein='pactl load-module module-loopback'
alias stoplinelin='pactl unload-module module-loopback'
alias ping254='ping 192.168.1.254 -i 1 -s 1'
alias pinga='ping -i 0.5 -s 9000'
alias pingg='ping goo.gl -i 1 -s 1'
alias noscreenoff='xset s noblank'
alias screenoff='xset s blank'
alias soff='xset dpms force off'
alias nfi='clear; neofetch'
alias nvv='ncmpcpp --screen visualizer'
alias nll='ncmpcpp --screen playlist'
alias cls='clear'
alias rg='ranger'
#alias ls='ls -hal --color=auto'
alias dir='dir --color=auto'
alias w3m='cd ~/w3m/ && w3m'
alias w3mm='cd ~/w3m/ && w3m -cookie'
alias hh='cd ~/'
alias mv='mv -i'
alias rm='rm -i'

