#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config border_radius       20
bspc config window_gap          12
bspc config left_padding        20
bspc config right_padding       20
bspc config top_padding         24
bspc config bottom_padding      16

bspc config split_ratio          0.58
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc rule -a Chromium desktop='^2'
bspc rule -a qutebrowser desktop='^2'
bspc rule -a Thunar desktop='^3'
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Steam desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a URxvt:urxvtf floating=on
bspc rule -a vlc state=floating




sxhkd &
sleep 0.5; urxvt &
sleep 0.5; urxvt &
sleep 1; urxvt -g 60x18 -e sh -c "while true; do ncmpcpp -c ~/.ncmpcpp/config_float; done" &
sleep 1; bspc node -t pseudo_tiled &
sh ~/.scripts/compton.sh &
flashfocus &
sh ~/.scripts/dunst_reload.sh &
sleep 2; bspc node -f west &
polybar nepu &


bspc config normal_border_color "#000000"
bspc config actived_border_color "#000000"
bspc config focused_border_color "#000000"
bspc config presel_feedback_color "#7d7648"
